library json_mapper.dynamic_mapper_factory;

import 'dart:mirrors';

import 'dart:convert';

import 'package:json_mapper/src/abstract_mapper_factory.dart';
import 'package:json_mapper/json_mapper.dart';
import 'package:json_mapper/metadata.dart';
import 'package:json_mapper/src/builder_field_mapper.dart';

part 'src/dynamic_mapper.dart';

/// Initialize the mapper system.
///
/// It's necessary to call this method before encoding or decoding
/// any object. When using json_mapper on the client side, it's
/// necessary to call this method from the `main()` function, so during
/// `pub build`, it can be replaced by `staticBootstrapMapper()`, which uses
/// static data generated by the json_mapper's tranformer to encode and
/// decode objects.
///
///      main() {
///        ...
///        bootstrapMapper();
///        ...
///      }
void bootstrapMapper() => configure(_dynamicMapper);
